### ISSUE TITLE
ModuleNotFoundError: No module named 'sync_batchnorm'

### ISSUE THREAD

**Issue by AIGirl10** [snehitvaddi/Deep-Fake_First_Order_Model#5]
Error while running colab file, **_Create a model and load checkpoints_** section.
```
ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-21-d44e78715a55> in <module>()
----> 1 from demo import load_checkpoints
      2 generator, kp_detector = load_checkpoints(config_path='/content/config/vox-256.yaml', 
      3                             checkpoint_path='/content//My Drive/first-order-motion-model/vox-cpk.pth.tar')

/content/Deep-Fake_First_Order_Model/demo.py in <module>()
     11 
     12 import torch
---> 13 from sync_batchnorm import DataParallelWithCallback
     14 
     15 from modules.generator import OcclusionAwareGenerator

ModuleNotFoundError: No module named 'sync_batchnorm'

```

Can you please met me know whats the issue ?

**Comment by snehitvaddi** [comment]
It worked fine in the past, but still figuring out why.

Will get back, ones found the solution.

**Comment by chaerlo** [comment]
problem +1,
ModuleNotFoundError: No module named 'sync_batchnorm'

**Comment by AIGirl10** [comment]
@snehitvaddi @XieLeo11 

problem solved. You need to use sync_batchnorm module from original repository: [here it is](https://github.com/AliaksandrSiarohin/first-order-model)

**Comment by AIGirl10** [comment]
Closing issue, since its solved. Reopen if have doubts.
